# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0002_auto_20160531_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='droppedout',
            field=models.BooleanField(default=0, max_length=1),
        ),
    ]
