# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0004_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colleges',
            new_name='College',
        ),
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
