# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrnd', '0005_auto_20160602_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mrnd.Student'),
        ),
    ]
